### PR TITLE
Docs: CODE_OF_CONDUCT.md

### LINKED ISSUE #514: contributing.md : not working
when I click on contributing guidline link it show nothing. 
Screenshot 2023-09-06 064506

### LINKED ISSUE #517: code of conduct.md : is not available
why we need this 👍 
A code of conduct defines standards for how to engage in a community. It signals an inclusive environment that respects all contributions.

### PR DESCRIPTION
**Pull request by Madhurchandran**
#### What type of PR is this?
/kind documentation:- code_of_conduct.md

#### What this PR does / why we need it:
We as members, contributors, and leaders pledge to make participation in our community a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

We pledge to act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community.

#### Which issue(s) this PR fixes:

Fixes #514 #517

#### Special notes for your reviewer:
if you have further enquiry regarding code of conduct file something need to be change let me know. I'll try my best to fix it.

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., design docs, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Madhurchandran** [comment]
@SparkYuan I made pull request request again

**Comment by SparkYuan** [comment]
@Madhurchandran Commit lint failed. Please amend your commit messages to follow the commit convention. 

https://github.com/conventional-changelog/commitlint/#what-is-commitlint

**Comment by SparkYuan** [comment]
@Madhurchandran Could you please clarify why there is an empty file named "code"? Is it pushed by mistake?

**Comment by SparkYuan** [comment]
> @SparkYuan sorry it pushed by mistake, can i try again and remove this code file then make new pull request.

There is no need to create a new PR. You can amend your commit history with `git commit --amend` or `git rebase` on this PR. Here is a tutorial about how to amend your git history: https://www.atlassian.com/git/tutorials/rewriting-history

You can also google these two commands for more details.

**Comment by healthjyk** [comment]
Hi there! I have already added `contributing.md`. You can add a section *Code of Conduct* in the `contributing.md` and ref  to the article `CODE_OF_CONDUCT.md` you added.

**Comment by Madhurchandran** [comment]
@healthjyk I already created CODE_OF_CONDUCT.md file so you want add reference link in contributing.md file.

**Comment by SparkYuan** [comment]
> @healthjyk I already created CODE_OF_CONDUCT.md file so you want add reference link in contributing.md file.

@Madhurchandran CODE_OF_CONDUCT is necessary. After this PR is merged, you can also modify the contributing.md file to add a reference link.

**Comment by Madhurchandran** [comment]
@healthjyk why we need amend someone already deleted code file which is pushed by mistake.

**Comment by SparkYuan** [comment]
> @healthjyk why we need amend someone already deleted code file which is pushed by mistake.



> @healthjyk why we need amend someone already deleted code file which is pushed by mistake.

Your previous commit messages don't pass the `Constraints / Commit Lint (pull_request) ` validation. You can [squash all your commits and modify the commit messages](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together) like "docs: add CODE_OF_CONDUCT" to pass this validation. Once the CI validation has been successfully completed, we may proceed to approve this PR.

**Comment by SparkYuan** [comment]
> yes i need help @SparkYuan

I do not have permission to push code to your repository. You can follow the instructions below to create a new PR.
1. fork a new branch named `code-of-conduct` from the latest **origin** main branch in your repo. NOT your current local main branch!!!
2. create a new file named `code_of_conduct.md` in the directory `kusion/docs`
3. copy your contents into the new file
4. push this branch to your repo and create a new PR.

feel free to contact me if you have any questions :)

**Comment by SparkYuan** [comment]
@Madhurchandran Your current commit history is already messy. Please fork a new branch and avoid making further changes based on the current main branch.

You can also join our [Slack](https://join.slack.com/t/kusionstack/shared_invite/zt-19lqcc3a9-_kTNwagaT5qwBE~my5Lnxg) to communicate more efficiently.

**Review by SparkYuan — APPROVED** [review]
lgtm

**Comment by SparkYuan** [comment]
@Madhurchandran Thank you so much for your contributions. I got an idea to help you to fix the commit history. All commits will be squashed before they can merged into the main branch, I can utilize this feature to fix your commits.

**Pull request merged**
