### PR TITLE
feat: support path-style of bucket for s3 storage backend

### LINKED ISSUE #1178: Feat: Support Path-Style of bucket for s3 Storage backend
### What would you like to be added?

The Path-Style bucket link for the S3 storage option.

### Why is this needed?

Currently, the endpoint of S3 is only in Virtual-hosted–style: https://bucket_name.s3.example.com/. The error will occur if in the case of S3 Storage Server only supports Certificate for Path-Style like https://s3.example.com/bucket_name/
```sh
✘  get workspaces meta data from s3 failed: RequestError: send request failed
      caused by: Get "https://bucket_name.s3.example.com/.metadata.yml": tls: failed to verify certificate: x509: certificate is valid for *.example.com, example.com, not bucket_name.s3.example.com`
```

### PR DESCRIPTION
**Pull request by hoangndst**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Currently, the endpoint of S3 is only in Virtual-hosted–style: https://bucket_name.s3.example.com/. The error will occur if in the case of S3 Storage Server only supports Certificate for Path-Style like https://s3.example.com/bucket_name/
#### Which issue(s) this PR fixes:

Fixes #1178

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., design docs, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by hoangndst** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by liu-hm19** [comment]
@hoangndst Thank you very much for submitting this pull request! This PR looks good to me, but it didn't pass the **Commit Lint** check. We would appreciate it if you could update the commit message in the following format and push it again. 

```shell
# reset the commit
git reset --soft HEAD^

# update the commit message
git commit -m "feat: force path-style"

# force push to the remote branch
git push [remote-repo] s3-path-style:s3-path-style -f
```

**Review by liu-hm19 — APPROVED** [review]
lgtm, thanks a lot for submitting this pull request! Please update the commit message and push the branch again to pass the **Commit Lint** check.

**Comment by hoangndst** [comment]
Okay, I'll fix it soon! 😅

**Comment by SparkYuan** [comment]
@hoangndst Thank you very much for your contribution! Welcome to the community!

**Pull request merged**
