### PR TITLE
feat: upgrade the appconfiguration generator framework

### PR DESCRIPTION
**Pull request by Wenfeng-GAO**
Refs: #529

#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:

Refs #529 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., design docs, usage docs, etc.:

```docs
- [Design]: <https://github.com/KusionStack/kusion/pull/565/files>

```

### CODE REVIEW

**Comment by elliotxx** [comment]
Need to repair the unit test 👆🏻

**Review by elliotxx — APPROVED** [review]
lgtm

**Review by SparkYuan — CHANGES_REQUESTED** [review]
71 of 128 (55.47%) changed or added relevant lines in 6 files are covered.

Test coverage is too low, please add more test cases.

**Review by SparkYuan — APPROVED** [review]

**Review by SparkYuan — APPROVED** [review]
lgtm

**Pull request merged**
