### PR TITLE
fix: the latter volume dirs overwrite the prior one

### LINKED ISSUE #1213: Fix Dir volumes
### What happened?

If there are multiple containers, the later container volumes (sort by alphabet) config will overwrite all volumes.

### What did you expect to happen?

deployment volume map correctly

### How can we reproduce it (as minimally and precisely as possible)?

```
import kam.v1.app_configuration as ac
import service
import service.container as c
import network as n
import monitoring as m
import mysql
import service.container.probe as p

score_compose: ac.AppConfiguration {
    workload: service.Service {
        annotations: {
            "prefix.com/Another-Key_Annotation.2": "something else"
            "compose.score.dev/workload-name": "example-workload-name123"
        }
        replicas: 1
        containers: {
            container_one1: c.Container {
                image: "localhost:4000/repo/my-image:tag"
                dirs: {
                    "/abcd": "secret://sec-name/key"
                }
            }
            hello2: c.Container {
                image: "busybox2"
            }
        }
    }
}
```

hello2 don't have dirs so generated deployment for container_one1 won't have volumes

### Anything else we need to know?

_No response_

### Kusion version

<details>

```console
$ kusion version
releaseVersion: 0.12.0
gitInfo:
    latestTag: v0.12.0
    commit: 88c4a179f71eb67b710736434691423213013530
    treeState: clean
buildInfo:
    goVersion: go1.22.4
    GOOS: linux
    GOARCH: amd64
    numCPU: 4
    compiler: gc
    buildTime: "2024-06-12 12:48:49"
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

$ uname -a
Linux vietanht-16Z90Q-GA56K 6.8.0-36-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun 10 10:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### PR DESCRIPTION
**Pull request by vietanhtwdk**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Fix volumes deployment

#### Which issue(s) this PR fixes:

Fixes #1213 
#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., design docs, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by vietanhtwdk** [comment]
I assume that configMaps have same problem but not tested yet

**Comment by vietanhtwdk** [comment]
recheck

**Comment by SparkYuan** [comment]
> recheck

Thanks for your feedback! Please sign the CLA by just posting a comment mentioned above and modifying your comment message and PR title accounting to the constraints in the CI.

**Comment by vietanhtwdk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by liu-hm19 — APPROVED** [review]
lgtm

**Comment by liu-hm19** [comment]
@vietanhtwdk Thanks a lot for your contribution! This PR looks good to me, and it has been merged. Welcome to become one of the contributors of Kusion 👍 Hope you enjoy this journey : )

**Pull request merged**
