### PR TITLE
fix: typo in destroy.go and destroy_test.go filenames

### PR DESCRIPTION
**Pull request by EdenBW**
Fixes typo as described in https://github.com/KusionStack/kusion/issues/1250

### CODE REVIEW

**Comment by EdenBW** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by liu-hm19** [comment]
@EdenBW Hi! It seems that this PR did not pass the **Commit Lint** check. Could you please modify the PR title and the commit message in the format of `fix: typo in destroy.go and destroy_test.go filenames`, and resubmit again? Thank you very much!

**Comment by EdenBW** [comment]
@liu-hm19 I've fixed the commit message and PR title.

**Review by liu-hm19 — APPROVED** [review]
lgtm

**Comment by liu-hm19** [comment]
@EdenBW Hi, your PR has been merged successfully. Thanks a lot for your contributions, and welcome to the **KusionStack** community! Please feel free to communicate and discuss with us : )

**Pull request merged**
