### PR TITLE
update kusion engine arch img

### PR DESCRIPTION
**Pull request by SparkYuan**
Add more details in kusion engine arch img

### CODE REVIEW

**Comment by howieyuen** [comment]
cannot see the details from the tiny PNG, could you please add some description?

**Comment by SparkYuan** [comment]
> cannot see the details from the tiny PNG, could you please add some description?

add specified operations and state storages in the arch image to make it easier to understand

**Comment by SparkYuan** [comment]
> cannot see the details from the tiny PNG, could you please add some description?

add specified operations and state storages in the arch image to make it easier to understand

**Review by markliby — APPROVED** [review]
lgtm

**Review by howieyuen — APPROVED** [review]

**Pull request merged**
