### PR TITLE
feat: add random string function for upcoming secret generator refact

### PR DESCRIPTION
**Pull request by adohe**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
add random string function for upcoming secret generator refact
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., design docs, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liu-hm19** [comment]
Where will this method be used? If a randomly generated string based on the current time is added to the rendering logic of application resources, it may potentially cause changes in the generated `Spec` or `Intent` with every `build`/`preview`/`apply` operation, which might have an impact on the 3-way diff process.

**Comment by ffforest** [comment]
Is this only used for non-terraform resources? For terraform resources we should just use the `random` provider - provides same functionality and handles diff already.

**Comment by adohe** [comment]
> Is this only used for non-terraform resources? To generate secrets in terraform resources we should just use the `random` provider - provides same functionality and handles diff already.

This is only used for secret generator, so we put this package under secret.

**Comment by adohe** [comment]
> Where will this method be used? If a randomly generated string based on the current time is added to the rendering logic of application resources, it may potentially cause changes in the generated `Spec` or `Intent` with every `build`/`preview`/`apply` operation, which might have an impact on the 3-way diff process.

This method will be used to generate random token string if and only if developers don't provide one in configuration als the impact on diff logic is as expected.

**Review by elliotxx — APPROVED** [review]
lgtm

**Pull request merged**
