### PR TITLE
docs: update links in readme

### LINKED ISSUE #306: Some links in readme are outdated
Some links in Readme are no longer accessible, we should update or delete them

For example:

https://github.com/KusionStack/kusion/blob/b7265ac54014bf8e0a71da53cee2c76e403f4d42/README.md?plain=1#L65

I will submit a PR to fix it soon

### PR DESCRIPTION
**Pull request by jakezhu9**
#### What type of PR is this?
/kind documentation

Updated inaccessible links in README
Replace some links in the Readme-zh with Chinese documentation links

#### Which issue(s) this PR fixes:

Fixes #306

### CODE REVIEW

**Comment by jakezhu9** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jakezhu9** [comment]
recheck

**Comment by SparkYuan** [comment]
@jakezhu9 LGTM
Welcome new contributors 👏🏻

**Review by SparkYuan — APPROVED** [review]
LGTM
Welcome new contributors 👏🏻

**Pull request merged**
